const SUCCESS = 20000
const FAILURE = 40000
const INTERNAL_FAILURE = 50000

const SEND_CODE_FREQRUNED = 40009

const USER_NOT_EXISTS = 40004
const USER_ALREADY_EXISTS = 40009
const USERNAME_NOT_MATCH_EMAIL = 40000
const USERNAME_OR_EMAIL_IS_EMPTY = 40000
const USERNAME_OR_PASSWORD_IS_INCORRECT = 40000
const USERNAME_OR_PASSWORD_IS_EMPTY = 40000
const USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY = 40000

module.exports = {
  SUCCESS,
  FAILURE,
  SEND_CODE_FREQRUNED,
  INTERNAL_FAILURE,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  USERNAME_NOT_MATCH_EMAIL,
  USERNAME_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_INCORRECT,
  USERNAME_OR_PASSWORD_IS_EMPTY,
  USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY,
}
