const SUCCESS = 20000
const FAILURE = 40000
const INTERNAL_FAILURE = 50000

const SEND_CODE_FREQRUNED = 40009

const USER_NOT_EXISTS = 40004
const USER_ALREADY_EXISTS = 40009
const USERNAME_NOT_MATCH_EMAIL = 40000
const USERNAME_OR_EMAIL_IS_EMPTY = 40000
const USERNAME_OR_PASSWORD_IS_INCORRECT = 40000
const USERNAME_OR_PASSWORD_IS_EMPTY = 40000
const USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY = 40000
const USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY = 40000
const CODE_INCORRECT = 40000
const CODE_EXPIRED = 40000
const EITHER_OLDPASSWORD_OR_NEWPASSWORD_IS_EMPTY = 40000
const PASSWORD_FORMAT_ERROR = 40000
const OLDPASSWORD_ERROR = 40000

const TOEKN_ID_IS_EMPTY = 40000
const TOKEN_NOT_EXISTS = 40000
const THE_TOKEN_NOT_EXISTS = 40000
const POOL_NOT_EXIST = 40004
const TOKEN_ID_OR_NUMBER_IS_EMPTY = 40000
const NOT_ENOUGH_BALANCE = 40000

const FOBIDDEN = 40003

module.exports = {
  SUCCESS,
  FAILURE,
  SEND_CODE_FREQRUNED,
  INTERNAL_FAILURE,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  USERNAME_NOT_MATCH_EMAIL,
  USERNAME_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_INCORRECT,
  USERNAME_OR_PASSWORD_IS_EMPTY,
  USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY,
  CODE_INCORRECT,
  CODE_EXPIRED,
  FOBIDDEN,
  EITHER_OLDPASSWORD_OR_NEWPASSWORD_IS_EMPTY,
  PASSWORD_FORMAT_ERROR,
  OLDPASSWORD_ERROR,
  TOEKN_ID_IS_EMPTY,
  TOKEN_NOT_EXISTS,
  POOL_NOT_EXIST,
  TOKEN_ID_OR_NUMBER_IS_EMPTY,
  NOT_ENOUGH_BALANCE,
  THE_TOKEN_NOT_EXISTS,
}
