const SUCCESS = '请求成功'
const FAILURE = '请求出错'
const INTERNAL_FAILURE = '服务器出错'

const SEND_CODE_FREQRUNED = '发送验证码过于频繁，请稍后再试'

const USER_NOT_EXISTS = '用户不存在'
const USER_ALREADY_EXISTS = '用户已存在'
const USERNAME_NOT_MATCH_EMAIL = '用户名与邮箱不匹配'
const USERNAME_OR_EMAIL_IS_EMPTY = '用户名或邮箱不能为空'
const USERNAME_OR_PASSWORD_IS_INCORRECT = '用户名或密码错误'
const USERNAME_OR_PASSWORD_IS_EMPTY = '用户名或密码不能为空'
const USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY = '用户名，密码或邮箱不能为空'
const USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY = '用户名，密码或验证码不能为空'

const CODE_INCORRECT = '验证码错误'
const CODE_EXPIRED = '验证码过期'

module.exports = {
  SUCCESS,
  FAILURE,
  SEND_CODE_FREQRUNED,
  INTERNAL_FAILURE,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  USERNAME_NOT_MATCH_EMAIL,
  USERNAME_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_EMPTY,
  USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_INCORRECT,
  USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY,
  CODE_INCORRECT,
  CODE_EXPIRED,
}
