const SUCCESS = '请求成功'
const FAILURE = '请求出错'
const FOBIDDEN = '非法请求'
const INTERNAL_FAILURE = '服务器出错'

const CODE_INCORRECT = '验证码错误'
const CODE_EXPIRED = '验证码过期'
const SEND_CODE_FREQRUNED = '发送验证码过于频繁，请稍后再试'

const UID_IS_EMPTY = 'UID 不能为空'
const USER_NOT_EXISTS = '用户不存在'
const USER_ALREADY_EXISTS = '用户已存在'
const OLDPASSWORD_ERROR = '旧密码错误'
const PASSWORD_FORMAT_ERROR = '新密码格式不正确'

const NOT_ENOUGH_BALANCE = '余额不足'
const POOL_NOT_EXIST = '该交易对无流动性池子'

const STAKE_ID_NOT_EXIST = '质押不存在'
const UID_STAKE_ID_NOT_MATCHED = 'UID, 质押 ID 不匹配'
const UID_OR_STAKE_ID_IS_EMPTY = 'UID, 质押 ID 不能为空'

const THE_TOKEN_NOT_EXISTS = '该 Token 不存在'
const TOKEN_NOT_EXISTS = '转入或转出 TokenID 不存在'
const TOEKN_ID_IS_EMPTY = '转入或转出 TokenID 不能为空'
const TOKEN_ID_OR_STAKE_NUMBER_IS_EMPTY = 'Token, 质押数量不能为空'
const TOKEN_ID_OR_NUMBER_IS_EMPTY = '转出数量，转入或转出 TokenID 不能为空'

const USERNAME_NOT_MATCH_EMAIL = '用户名与邮箱不匹配'
const USERNAME_OR_EMAIL_IS_EMPTY = '用户名或邮箱不能为空'
const USERNAME_OR_PASSWORD_IS_EMPTY = '用户名或密码不能为空'
const USERNAME_OR_PASSWORD_IS_INCORRECT = '用户名或密码错误'
const USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY = '用户名, 密码或邮箱不能为空'
const USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY = '用户名, 密码或验证码不能为空'
const EITHER_OLDPASSWORD_OR_NEWPASSWORD_IS_EMPTY = '旧密码或新密码为空'

module.exports = {
  SUCCESS,
  FAILURE,
  FOBIDDEN,
  INTERNAL_FAILURE,

  CODE_EXPIRED,
  CODE_INCORRECT,
  SEND_CODE_FREQRUNED,

  POOL_NOT_EXIST,
  STAKE_ID_NOT_EXIST,

  UID_IS_EMPTY,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  USERNAME_NOT_MATCH_EMAIL,
  USERNAME_OR_EMAIL_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_EMPTY,
  USERNAME_OR_PASSWORD_IS_INCORRECT,
  USERNAME_OR_PASSWORD_OR_CODE_IS_EMPTY,
  USERNAME_OR_PASSWORD_OR_EMAIL_IS_EMPTY,

  OLDPASSWORD_ERROR,
  PASSWORD_FORMAT_ERROR,
  EITHER_OLDPASSWORD_OR_NEWPASSWORD_IS_EMPTY,

  TOKEN_NOT_EXISTS,
  TOEKN_ID_IS_EMPTY,
  THE_TOKEN_NOT_EXISTS,
  TOKEN_ID_OR_NUMBER_IS_EMPTY,
  TOKEN_ID_OR_STAKE_NUMBER_IS_EMPTY,

  NOT_ENOUGH_BALANCE,

  UID_OR_STAKE_ID_IS_EMPTY,
  UID_STAKE_ID_NOT_MATCHED,
}
